"""Pydantic schemas for planner outputs and run artifacts."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class ReviewRequest(BaseModel):
    """Structured review request generated by the planner."""

    skill: Literal["review-r", "review-julia", "review-tex", "review-comments"]
    target: str = Field(min_length=1)


class NextIncrement(BaseModel):
    """Minimal next increment returned by the planner."""

    objective: str = Field(min_length=1)
    files_to_touch: list[str] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)
    verification_commands: list[str] = Field(default_factory=list)
    review_requests: list[ReviewRequest] = Field(default_factory=list)
    acceptance_criteria: list[str] = Field(default_factory=list)


class PlannerDecision(BaseModel):
    """Validated planner response payload."""

    status: Literal["continue", "done", "blocked"]
    why_called: Literal["initial", "stalled", "cross_cutting", "final_review"]
    diagnosis: str = Field(min_length=1)
    risk_flags: list[str] = Field(default_factory=list)
    next_increment: NextIncrement
    questions_for_user: list[str] = Field(default_factory=list)
    stop_if: list[str] = Field(default_factory=list)


class FailureSignature(BaseModel):
    """Normalized verification failure signature."""

    command: str
    exit_code: int
    normalized_signature: str
    first_error_line: str = ""
    relevant_tail: str = ""


class ContextManifest(BaseModel):
    """Metadata describing what context was assembled for a run."""

    task: str
    scope_paths: list[str] = Field(default_factory=list)
    included_files: list[str] = Field(default_factory=list)
    included_logs: list[str] = Field(default_factory=list)
    included_reviews: list[str] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)


class UsageSummary(BaseModel):
    """Planner usage summary for final reports."""

    input_tokens: int = 0
    output_tokens: int = 0
    total_tokens: int = 0
    estimated_cost_usd: float = 0.0


class RunManifest(BaseModel):
    """High-level manifest for a thorny-loop run directory."""

    run_id: str
    task: str
    status: Literal["pending", "running", "done", "blocked", "failed"]
    planner_model: str
    planner_calls: int = 0
    coder_turns: int = 0
    files_changed: list[str] = Field(default_factory=list)
    verify_steps: list[str] = Field(default_factory=list)
    reviews_run: list[str] = Field(default_factory=list)
    usage_summary: UsageSummary = Field(default_factory=UsageSummary)
